name: deploy app

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install yarn
        run: npm install --global yarn

      - name: Install packages with yarn
        run: yarn install

      - name: Builds the app for production
        run: yarn run build

      - name: Set git user information
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
        env:
          USER_NAME: kisstar
          USER_EMAIL: dwh.chn@foxmail.com

      - name: Deploy with gh-pages for GitHub
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: kisstar/notebook
          branch: gh-pages
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy with gh-pages for Gitee
        uses: kisstar/git-pages-action@main
        with:
          git-hosts: gitee.com
          repository-name: dongwanhong/notebook
          branch: gh-pages
          folder: docs/.vuepress/dist
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
