name: deploy app

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Install yarn
        run: npm install --global yarn

      - name: Install packages with yarn
        run: yarn install

      - name: Builds the app for production
        run: yarn run build

      - name: Deploy to GitHub using gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d docs/.vuepress/dist -b gh-pages
          git remote remove origin
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: notebook

      - name: Set ssh key
        run: |
          mkdir -p ~/.ssh
          echo "$GITEE_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "$GITEE_IP" >> ~/.ssh/known_hosts
        env:
          GITEE_IP: 212.64.63.190
          GITEE_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}

      - name: Deploy to Gitee using gh-pages
        run: |
          npx gh-pages -d docs/.vuepress/dist -b master -r git@gitee.com:dongwanhong/${GITEE_REPOSITORY}.git
        env:
          GITEE_REPOSITORY: notebook

      - name: Remove ssh key
        run: rm -rf ~/.ssh
